In [1]:
import numpy as np

a = np.random.randn(5)
# a.saphe = (5,)
# Don't use this

In [2]:
print(a)

[ 0.2508327  -0.68839296  0.55981679  0.16944304 -1.84140609]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.2508327  -0.68839296  0.55981679  0.16944304 -1.84140609]


In [5]:
print(np.dot(a,a.T))

4.2696840880322835


In [6]:
a = np.random.rand(5, 1)
# a.shape(5, 1) - column vector
print(a)

[[0.10312476]
 [0.30061848]
 [0.78011596]
 [0.47858184]
 [0.2351137 ]]


In [7]:
print(a.T)

[[0.10312476 0.30061848 0.78011596 0.47858184 0.2351137 ]]


In [8]:
print(np.dot(a, a.T))

[[0.01063472 0.03100121 0.08044927 0.04935364 0.02424604]
 [0.03100121 0.09037147 0.23451727 0.14387055 0.07067952]
 [0.08044927 0.23451727 0.60858091 0.37334933 0.18341595]
 [0.04935364 0.14387055 0.37334933 0.22904058 0.11252115]
 [0.02424604 0.07067952 0.18341595 0.11252115 0.05527845]]


In [17]:
# Kiểm tra a.shape có là (5, 1) hay không?
assert(a.shape == (5, 1))

In [ ]:
# Có thể sử dụng reshape 